package org.springframework.data.xap.integration;

import junit.framework.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.xap.model.Event;
import org.springframework.data.xap.repository.EventRepository;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.util.Arrays;

import static junit.framework.TestCase.assertNotNull;

/**
 * Tests that repository save operations work with autogenerated id
 *
 * @author Oleksiy_Dyagilev
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class AutoGeneratedIdTest {

    @Autowired
    private EventRepository eventRepository;

    @Test
    public void testSaveWithAutogeneratedId() {
        Event event = new Event();
        event.setName("event1");
        Event saved = eventRepository.save(event);
        assertNotNull(saved.getId());
    }

    @Test
    public void testSaveMultipleWithAutogeneratedId() {
        Event event1 = new Event();
        event1.setName("event1");

        Event event2 = new Event();
        event2.setName("event2");

        Iterable<Event> save = eventRepository.save(Arrays.asList(event1, event2));

        for (Event event : save) {
            assertNotNull(event.getId());
        }
    }
}
