---
tags: [xap, spring-data]
projects: [spring-data-xap]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-accessing-data-xap

This guide walks you through the process of building an application with GigaSpaces XAP.

== What you'll build

You will use the powerful Spring Data XAP library to store and retrieve POJOs.

== What you'll need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]


[[initial]]
== Define a simple entity
GigaSpaces XAP is in-memory data grid. It stores data into spaces, and each space can be configured in different manner(replicated, partitioned etc).
For this guide you use an embedded space so you don't have to set up anything extra.

In this example, you store Book objects with a few annotations.

`src/main/java/hello/Book.java`
[source,java]
----
include::complete/src/main/java/hello/Book.java[]
----

Here you have a `Book` class with three attributes, the `id`, the `author` and the `copies`. You also have the constructor to populate the entities when creating a new instance and the default constructor.

Notice that this class is annotated `@SpaceClass`. This annotation is not mandatory, you can write netity to the space without it, but it's used to provide an additional metadata.
This class also has getter for `id` marked with `@SpaceId`. This property uniquely identifies the entity within the space, and is similar to a primary key in a database.

The next important piece is the number of book's copies. Later in this guide, you will use it to fashion some queries.

The convenient `toString()` method will print out the book's id, author and copies.

== Start embedded space
Run hello.SpaceStarter main method from your favorite IDE and leave that process in background

== Create simple queries
Spring Data XAP focuses on storing data in XAP. It also inherits powerful functionality from the Spring Data Commons project, such as the ability to derive queries. Essentially, you don't have to learn the query language of GigaSpaces XAP; you can simply write a handful of methods and the queries are written for you.

To see how this works, create an interface that queries `Book` space objects.

`src/main/java/hello/BookRepository.java`
[source,java]
----
include::complete/src/main/java/hello/BookRepository.java[]
----

`BookRepository` extends the `CrudRepository` interface and plugs in the type of values and keys it works with: `Book` and `String`. Out-of-the-box, this interface comes with many operations, including standard CRUD (create-read-update-delete).

You can define other queries as needed by simply declaring their method signature. In this case, you add `findByAuthor`, which essentially seeks entities of type `Book` and find the ones that matches on `Author`.

You also have:

- `findByCopiesLessThan` to find books with a number of copies below a certain number
- `findByAuthorOrCopiesGreaterThan` to find books with a certain author or number of copies above a certain number

Let's wire this up and see what it looks like!

== Create an application class
Here you create an Application class with all the components.

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

In the configuration, you need to add the `@EnableXapRepositories` annotation.

XAP space is required to store all data. For that, you have Spring Data XAP convenient `SpaceClient` bean.

NOTE: In this guide, the space is created locally using built-in components and an evaluation license. For a production solution, Spring recommends the production version of XAP, where you can create distributed spaces across multiple nodes.

NOTE: The types are `<String, Book>`, matching the key type (`String`) with the value type (`Book`).

The `public static void main` uses Spring Boot's `SpringApplication.run()` to launch the application and invoke the `CommandLineRunner` that builds the relationships.

The application autowires an instance of `BookRepository` that you just defined. Spring Data XAP will dynamically create a concrete class that implements that interface and will plug in the needed query code to meet the interface's obligations. This repository instance is the used by the `run()` method to demonstrate the functionality.

== Store and fetch data
In this guide, you are creating three local `Book` s, **SpringInAction**, **ThinkingInJava**, and **EffectiveJava**. Initially, they only exist in memory. After creating them, you have to save them to XAP.

Now you run several queries. The first looks up books by author. Then you execute query to find less popular books and another query to find popular books or books written by specific author.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_mainhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


You should see something like this:
....
Before writing objects to space...
	Book{id='1234', author='Eccel', copies=10000}
	Book{id='2345', author='Bloch', copies=20000}
	Book{id='3456', author='Walls', copies=50000}
Lookup books by author...
	[Book{id='1234', author='Eccel', copies=10000}]
	[Book{id='2345', author='Bloch', copies=20000}]
	[Book{id='2345', author='Bloch', copies=20000}]
Lookup for less popular books...
	Book{id='1234', author='Eccel', copies=10000}
Lookup for popular books or books of specific author...
	Book{id='2345', author='Bloch', copies=20000}
	Book{id='3456', author='Walls', copies=50000}
....

== Summary
Congratulations! You set up an embedded XAP space, stored simple entities, and developed quick queries.
